### ISSUE TITLE
graylog.json ISO 404

### ISSUE THREAD

**Issue by chrisdinozzi** [tothi/ad-honeypot-autodeploy#3]
hiya,

when running packer-build-all.sh the download link inside graylog.json returns a 404.

I replaced it with 

https://old-releases.ubuntu.com/releases/18.04.5/ubuntu-18.04.5-server-amd64.iso

to get the same version of ubuntu, I haven't tested it with newer versions. the checksums match and it seems to be going fine.

anyone else faced this issue?

**Comment by tothi** [comment]
thanks for reporting.

updated the URL (and the checksum) to the new version: http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.6-server-amd64.iso

it is working now.
